### ISSUE TITLE
Blog Feedback

### ISSUE THREAD

**Issue by HorridModz** [Twi/blog2#1]
Hey, I just wanted to say that I love your blog! I found it from a google search and loved it so much I read all of your posts! I couldn't find a way to comment, and I don't use mastodon, so I found you on github and posted this here.

By the way, is there a way to subscribe to it?

**Comment by Twi** [comment]
Hi,

I haven't wanted to make comment support yet because I don't have the time to commit to moderation.

As for subscribing, please add http://friendshipcastle.zip/blog.rss to your RSS reader. I need to document this better.

Thanks!

**Comment by Twi** [comment]
I implemented comment support on my blogposts. You can sign in with GitHub OAuth and then you can comment to your heart's content.
